"""initial

Revision ID: 34921217e71e
Revises: 
Create Date: 2022-10-24 11:38:36.504718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34921217e71e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Status',
    sa.Column('idStatus', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idStatus')
    )
    op.create_table('User',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=45), nullable=True),
    sa.Column('FirstName', sa.String(length=45), nullable=False),
    sa.Column('SecondName', sa.String(length=45), nullable=False),
    sa.Column('Email', sa.String(length=45), nullable=True),
    sa.Column('Password', sa.String(length=45), nullable=False),
    sa.Column('Phone', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('UserName')
    )
    op.create_table('Drug',
    sa.Column('idDrug', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=45), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idStatus'], ['Status.idStatus'], ),
    sa.PrimaryKeyConstraint('idDrug')
    )
    op.create_table('Order',
    sa.Column('idOrder', sa.Integer(), nullable=False),
    sa.Column('idDrug', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idDrug'], ['Drug.idDrug'], ),
    sa.ForeignKeyConstraint(['idStatus'], ['Status.idStatus'], ),
    sa.ForeignKeyConstraint(['idUser'], ['User.idUser'], ),
    sa.PrimaryKeyConstraint('idOrder')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order')
    op.drop_table('Drug')
    op.drop_table('User')
    op.drop_table('Status')
    # ### end Alembic commands ###
